project:
  id: tpm
  name: Talan PM
  description: Project Management as Code
team:
  vlad.k:
    email: vladislav.kurmaz@gmail.com
    name: Vladyslav Kurmaz
    fte: 0.1
timeline:
  v0.15.0:
    deadline: 2025-01-14T18:00:00.000Z
  v0.14.0:
    deadline: 2025-01-07T18:00:00.000Z
  v0.13.0:
    deadline: 2024-12-30T14:00:00.000Z
  v0.12.0:
    deadline: 2024-12-21T19:00:00.000Z
  v0.11.0:
    deadline: 2024-12-09T08:00:00.000Z
  v0.10.0:
    deadline: 2024-11-17T21:40:00.000Z
  v0.9.0:
    deadline: 2024-11-10T21:00:00.000Z
  v0.8.0:
    deadline: 2024-11-03T12:00:00.000Z
  v0.7.0:
    deadline: 2024-10-28T21:55:00.000Z
  v0.6.0:
    deadline: 2024-10-22T15:30:00.000Z
  v0.5.0:
    deadline: 2024-09-23T15:30:00.000Z
  v0.4.0:
    deadline: 2024-09-15T15:30:00.000Z
  v0.3.0:
    deadline: 2024-09-12T15:30:00.000Z
  v0.2.0:
    deadline: 2024-09-04T15:30:00.000Z
tasks: |-
  [-:036:v0.14.0] Add UI controls @vlad.k
    [-] Dashboard
      [-] Checkbox for brief/full mode
      [-] Sort by deadline
    [-] Timeline
      [-] Tasks filter by statuses
      [-] Sort by deadline
    [-] Team
      [-] Search editbox
      [-] Sort by statuses
    [-] SRS
      [-] Search editbox
  [-:035:v0.14.0] Dump datetime in local time during update command @vlad.k
  [+:034:v0.14.0] Add update command --todo --dev --blocked --done to change task state @vlad.k
  [-:033:v0.14.0] Implement Timeline web part @vlad.k
  [-:032:v0.14.0] Add fs watch @vlad.k
    [-] Add --watch option to watch for changes in .todo.yml files and refresh tpm internal state
  [-:031:v0.14.0] Fix task output on hierarchy mode @vlad.k
  [+:030:v0.10.0] Implement deadline class @vlad.k
  [-:029:v0.14.0] Implement config command via source class @vlad.k
  [+:028:v0.14.0] Tasks spill over batch mode @vlad.k
  [+:027:v0.10.0] Implement team/member section as classes @vlad.k
  [+:026:v0.9.0] Implement srs section as classes @vlad.k
  [+:025:v0.9.0] Show SRS in UI @vlad.k
  [+:024:v0.14.0] Tweak task status based on child tasks (normalise) @vlad.k
  [+:023:v0.9.0] Implement project, team, srs section as classes @vlad.k
  [+:022:v0.7.0] Describe command - project @vlad.k
  [+:021:v0.6.0] Add project description section @vlad.k
  [+:020:v0.5.0] Add option to display tasks with different statuses: --backlog, --dev, --done @vlad.k
  [+:019:v0.5.0] Add component as optional parameter for ls command @vlad.k
  [-:018:v0.14.0] Generate snapshot @vlad.k
  [+:017:v0.5.0] Add SRS section @vlad.k
  [-:016:v0.14.0] Add describe command with resolved links @vlad.k
  [+:015:v0.5.0] Integrate .tpm folder at repository root level to store snapshots #invalid @vlad.k
  [+:014:v0.13.0] Update README.md with Hello World section using <https://github.com/project-talan/tln-demo> repository @vlad.k
  [+:013:v0.6.0] Add search @vlad.k
  [+:012:v0.6.0] Add CI/CD @vlad.k
  [+:011:v0.6.0] Add unit test framework @vlad.k
  [+:010:v0.6.0] Extract tags, timeline from task description @vlad.k
  [+:009:v0.5.0] Add command to generate .todo template --team, --timeline, --tasks, --force @vlad.k
  [+:008:v0.6.0] Merge multiple descriptions from one file @vlad.k
  [+:007:v0.12.0] Server command: express server + fs watch @vlad.k
    [+] Create API using express
    [+] Implement web part: Dashboard
    [+] Implement web part: Team
  [+:006:v0.4.0] Extract status, id, assingees from task description @vlad.k
  [+:005:v0.4.0] Implement ls command for timeline @vlad.k
  [+:004:v0.4.0] Implement ls for team @vlad.k
  [+:003:v0.3.0] Create hierarchy of nodes with descriptions @vlad.k
  [+:002:v0.2.0] Update README.md @vlad.k
  [+:001:v0.2.0] Read config with parameters (include, ignore etc.) @vlad.k
srs:
  ups: |
    The main project's USPs are:
      * 1
      * 2
