tasks: |-
  [-:003:0.20.0] Assistant section
  [-:002:0.20.0] Assessment section
    [-] Add collapse/expand for left/right menus
    [-] Add ability to save comments for any NFR/Stage
  [+:001:0.17.0] Improve Timeline section @vlad.k
    [+] Interval picker: week, month, quarter, year
    [+] Search by text
    [+] Check filtering by deadline
