tasks: |
  [-:003:0.19.0] Assistant - integration of hiring referral grid @vlad.k
  [-:002:0.19.0] Assistant - job description generation @vlad.k
  [-:001:0.19.0] Assistant - tasks generation @vlad.k

