name: "Base"

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: Ref to compare changes
      tests:
        type: string
        description: Tests
        default: "unit, static"
      build:
        type: boolean
        description: build
        default: false
      package-n-upload:
        type: boolean
        description: Package & Upload
        default: false
    secrets:
      SONAR_GITHUB_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "22.6.0"

      - run: npm i -g tln-cli@1.107.0 tln-pm@0.12.0

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init
        run: |
          npm i

      - name: Format & Unit test
        if: ${{ contains(inputs.tests, 'unit') }}
        run: |
          npm test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"

      - name: Build
        if: ${{ inputs.build }}
        run: |
          #npm build

      - name: Package and Upload
        if: ${{ inputs.package-n-upload }}
        run: |
          tln package:publish
