name: "Dispatch"

on:
  workflow_dispatch:
    inputs:
      tests:
        type: string
        description: Tests unit, static
      build:
        type: boolean
        description: Build
      package-n-upload:
        type: boolean
        description: Package & Upload

jobs:
  pipeline:
    permissions:
      deployments: write
      contents: read
    uses: ./.github/workflows/base.yaml
    with:
      tests: ${{ inputs.tests }}
      build: ${{ inputs.build }}
      package-n-upload: ${{ inputs.package-n-upload }}
    secrets:
      SONAR_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
