name: "Pull-request"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pipeline:
    permissions:
      deployments: write
      contents: read
    uses: ./.github/workflows/base.yaml
    with:
      ref: "origin/${{ github.event.pull_request.base.ref }}"
      tests: unit, static
      build: true
    secrets:
      SONAR_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
